package com.example.ffcs

data class ClsData(val fac:String,
    val slot:String,
    )
data class ro(var A1:String,
              var B1:String,
              var C1:String,
              var D1:String,
              var E1:String,
              var F1:String,
              var G1:String,
              var TA1:String,
              var TB1:String,
              var TC1:String,
              var TD1:String,
              var TE1:String,
              var TF1:String,
              var TG1:String,
              var TAA1:String,
              var TCC1:String,
              var A2:String,
              var B2:String,
              var C2:String,
              var D2:String,
              var E2:String,
              var F2:String,
              var G2:String,
              var TA2:String,
              var TB2:String,
              var TC2:String,
              var TD2:String,
              var TE2:String,
              var TF2:String,
              var TG2:String,
              var TAA2:String,
              var TCC2:String,
              var TDD2:String,
              var L1:String,
              var L2:String,
              var L3:String,
              var L4:String,
              var L5:String,
              var L6:String,
              var L7:String,
              var L8:String,
              var L9:String,
              var L10:String,
              var L11:String,
              var L12:String,
              var L13:String,
              var L14:String,
              var L15:String,
              var L16:String,
              var L17:String,
              var L18:String,
              var L19:String,
              var L20:String,
              var L21:String,
              var L22:String,
              var L23:String,
              var L24:String,
              var L25:String,
              var L26:String,
              var L27:String,
              var L28:String,
              var L29:String,
              var L30:String,
              var L31:String,
              var L32:String,
              var L33:String,
              var L34:String,
              var L35:String,
              var L36:String,
              var L37:String,
              var L38:String,
              var L39:String,
              var L40:String,
              var L41:String,
              var L42:String,
              var L43:String,
              var L44:String,
              var L45:String,
              var L46:String,
              var L47:String,
              var L48:String,
              var L49:String,
              var L50:String,
              var L51:String,
              var L52:String,
              var L53:String,
              var L54:String,
              var L55:String,
              var L56:String,
              var L57:String,
              var L58:String,
              var L59:String,
              var L60:String,
              var TBB2:String



)


data class ClsDatas(val datas:List<ClsData>,val title:String,var r:ro,
                     val id:Int?
)
